version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /
    ports:
      - "1111:1111"
    depends_on:
      - mariadb
  mariadb:
    image: moninoeurovisio/exercise-db_mariadb
    ports:
      - "3306:3306"